#!/usr/bin/env python3
"""Inference benchmark for the FSD trajectory‑prediction model.

- Loads the best checkpoint saved as ``models/fsd_v1.pth``.
- Generates a small number of synthetic samples using ``FSDDataset``.
- Runs a forward pass on each sample, measures per‑sample latency with
  ``time.perf_counter`` and reports the average latency.
- Prints the predicted waypoint tensor for each sample.

The script is intended to be run on the same hardware used for training
(Apple Silicon GPU via ``torch.backends.mps`` when available)."""

import os
import time
import torch
from dataset.fsd_dataset import FSDDataset
from models.fsd_net import FSDNet


def load_model(checkpoint_path: str = "models/fsd_v1.pth") -> torch.nn.Module:
    """Instantiate ``FSDNet`` and load weights from ``checkpoint_path``.
    ``checkpoint_path`` should point to the best model saved during training.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
    model = FSDNet().to(device)
    state = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(state)
    model.eval()
    return model, device


def benchmark(model, device, num_samples: int = 5):
    """Run inference on ``num_samples`` synthetic examples.
    Returns a list of (latency_seconds, predicted_waypoints) tuples.
    """
    # Use the synthetic dataset (same generation logic as training)
    dataset = FSDDataset(num_samples=num_samples, synthetic=True)
    loader = torch.utils.data.DataLoader(dataset, batch_size=1, shuffle=False)
    results = []
    with torch.no_grad():
        for idx, (cam, lidar, target) in enumerate(loader):
            cam = cam.to(device)
            lidar = lidar.to(device)
            start = time.perf_counter()
            pred = model(cam, lidar)
            latency = time.perf_counter() - start
            results.append((latency, pred.squeeze(0).cpu()))
            print(f"Sample {idx+1}: latency = {latency*1000:.2f} ms, predicted waypoints =\n{pred.squeeze(0).cpu().numpy()}")
    avg_latency = sum(r[0] for r in results) / len(results)
    print(f"\nAverage inference latency over {len(results)} samples: {avg_latency*1000:.2f} ms")
    return results


if __name__ == "__main__":
    # Path to the checkpoint generated by training (relative to repo root)
    checkpoint = os.path.join(os.path.dirname(__file__), "models", "fsd_v1.pth")
    if not os.path.exists(checkpoint):
        raise FileNotFoundError(f"Checkpoint not found at {checkpoint}. Run training first.")
    model, device = load_model(checkpoint)
    print(f"Model loaded on device: {device}")
    benchmark(model, device, num_samples=5)
